version: '3.8'

services:
  nginx:
    image: nginx:1.27.2-alpine
    container_name: upload
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src/public:/var/www/html
      - ./nginx:/etc/nginx.conf.d
    depends_on:
      - db
      - php-fpm
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"


  php-fpm:
    image: php:8.1-fpm-alpine
    container_name: php-fpm
    volumes:
      - ../src/public:/var/www/html 
  db:
    image: mysql:8.0
    container_name: upload_data
    # volumes:
    #   - ./storage/upload_data:/var/lib/mysql
    restart: no
    environment:
      MYSQL_INITDB_SKIP_TZINFO: "yes"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
